package poseidon2_plonky2

import g "github.com/elliottech/poseidon_crypto/field/goldilocks"

const (
	WIDTH = 12
	RATE  = 8
	OUT   = 4
	D     = 7
	// Generated by `poseidon2_round_numbers_128`
	ROUNDS_F      = 8
	ROUNDS_F_HALF = 4
	ROUNDS_P      = 22
)

var (
	// Generated randomly for ROUNDS_F
	EXTERNAL_CONSTANTS = [ROUNDS_F][WIDTH]g.GoldilocksField{
		{
			g.FromCanonicalUint64(15492826721047263190),
			g.FromCanonicalUint64(11728330187201910315),
			g.FromCanonicalUint64(8836021247773420868),
			g.FromCanonicalUint64(16777404051263952451),
			g.FromCanonicalUint64(5510875212538051896),
			g.FromCanonicalUint64(6173089941271892285),
			g.FromCanonicalUint64(2927757366422211339),
			g.FromCanonicalUint64(10340958981325008808),
			g.FromCanonicalUint64(8541987352684552425),
			g.FromCanonicalUint64(9739599543776434497),
			g.FromCanonicalUint64(15073950188101532019),
			g.FromCanonicalUint64(12084856431752384512),
		},
		{
			g.FromCanonicalUint64(4584713381960671270),
			g.FromCanonicalUint64(8807052963476652830),
			g.FromCanonicalUint64(54136601502601741),
			g.FromCanonicalUint64(4872702333905478703),
			g.FromCanonicalUint64(5551030319979516287),
			g.FromCanonicalUint64(12889366755535460989),
			g.FromCanonicalUint64(16329242193178844328),
			g.FromCanonicalUint64(412018088475211848),
			g.FromCanonicalUint64(10505784623379650541),
			g.FromCanonicalUint64(9758812378619434837),
			g.FromCanonicalUint64(7421979329386275117),
			g.FromCanonicalUint64(375240370024755551),
		},
		{
			g.FromCanonicalUint64(3331431125640721931),
			g.FromCanonicalUint64(15684937309956309981),
			g.FromCanonicalUint64(578521833432107983),
			g.FromCanonicalUint64(14379242000670861838),
			g.FromCanonicalUint64(17922409828154900976),
			g.FromCanonicalUint64(8153494278429192257),
			g.FromCanonicalUint64(15904673920630731971),
			g.FromCanonicalUint64(11217863998460634216),
			g.FromCanonicalUint64(3301540195510742136),
			g.FromCanonicalUint64(9937973023749922003),
			g.FromCanonicalUint64(3059102938155026419),
			g.FromCanonicalUint64(1895288289490976132),
		},
		{
			g.FromCanonicalUint64(5580912693628927540),
			g.FromCanonicalUint64(10064804080494788323),
			g.FromCanonicalUint64(9582481583369602410),
			g.FromCanonicalUint64(10186259561546797986),
			g.FromCanonicalUint64(247426333829703916),
			g.FromCanonicalUint64(13193193905461376067),
			g.FromCanonicalUint64(6386232593701758044),
			g.FromCanonicalUint64(17954717245501896472),
			g.FromCanonicalUint64(1531720443376282699),
			g.FromCanonicalUint64(2455761864255501970),
			g.FromCanonicalUint64(11234429217864304495),
			g.FromCanonicalUint64(4746959618548874102),
		},
		{
			g.FromCanonicalUint64(13571697342473846203),
			g.FromCanonicalUint64(17477857865056504753),
			g.FromCanonicalUint64(15963032953523553760),
			g.FromCanonicalUint64(16033593225279635898),
			g.FromCanonicalUint64(14252634232868282405),
			g.FromCanonicalUint64(8219748254835277737),
			g.FromCanonicalUint64(7459165569491914711),
			g.FromCanonicalUint64(15855939513193752003),
			g.FromCanonicalUint64(16788866461340278896),
			g.FromCanonicalUint64(7102224659693946577),
			g.FromCanonicalUint64(3024718005636976471),
			g.FromCanonicalUint64(13695468978618890430),
		},
		{
			g.FromCanonicalUint64(8214202050877825436),
			g.FromCanonicalUint64(2670727992739346204),
			g.FromCanonicalUint64(16259532062589659211),
			g.FromCanonicalUint64(11869922396257088411),
			g.FromCanonicalUint64(3179482916972760137),
			g.FromCanonicalUint64(13525476046633427808),
			g.FromCanonicalUint64(3217337278042947412),
			g.FromCanonicalUint64(14494689598654046340),
			g.FromCanonicalUint64(15837379330312175383),
			g.FromCanonicalUint64(8029037639801151344),
			g.FromCanonicalUint64(2153456285263517937),
			g.FromCanonicalUint64(8301106462311849241),
		},
		{
			g.FromCanonicalUint64(13294194396455217955),
			g.FromCanonicalUint64(17394768489610594315),
			g.FromCanonicalUint64(12847609130464867455),
			g.FromCanonicalUint64(14015739446356528640),
			g.FromCanonicalUint64(5879251655839607853),
			g.FromCanonicalUint64(9747000124977436185),
			g.FromCanonicalUint64(8950393546890284269),
			g.FromCanonicalUint64(10765765936405694368),
			g.FromCanonicalUint64(14695323910334139959),
			g.FromCanonicalUint64(16366254691123000864),
			g.FromCanonicalUint64(15292774414889043182),
			g.FromCanonicalUint64(10910394433429313384),
		},
		{
			g.FromCanonicalUint64(17253424460214596184),
			g.FromCanonicalUint64(3442854447664030446),
			g.FromCanonicalUint64(3005570425335613727),
			g.FromCanonicalUint64(10859158614900201063),
			g.FromCanonicalUint64(9763230642109343539),
			g.FromCanonicalUint64(6647722546511515039),
			g.FromCanonicalUint64(909012944955815706),
			g.FromCanonicalUint64(18101204076790399111),
			g.FromCanonicalUint64(11588128829349125809),
			g.FromCanonicalUint64(15863878496612806566),
			g.FromCanonicalUint64(5201119062417750399),
			g.FromCanonicalUint64(176665553780565743),
		},
	}

	// Generated randomly for ROUNDS_P
	INTERNAL_CONSTANTS = [ROUNDS_P]g.GoldilocksField{
		g.FromCanonicalUint64(11921381764981422944),
		g.FromCanonicalUint64(10318423381711320787),
		g.FromCanonicalUint64(8291411502347000766),
		g.FromCanonicalUint64(229948027109387563),
		g.FromCanonicalUint64(9152521390190983261),
		g.FromCanonicalUint64(7129306032690285515),
		g.FromCanonicalUint64(15395989607365232011),
		g.FromCanonicalUint64(8641397269074305925),
		g.FromCanonicalUint64(17256848792241043600),
		g.FromCanonicalUint64(6046475228902245682),
		g.FromCanonicalUint64(12041608676381094092),
		g.FromCanonicalUint64(12785542378683951657),
		g.FromCanonicalUint64(14546032085337914034),
		g.FromCanonicalUint64(3304199118235116851),
		g.FromCanonicalUint64(16499627707072547655),
		g.FromCanonicalUint64(10386478025625759321),
		g.FromCanonicalUint64(13475579315436919170),
		g.FromCanonicalUint64(16042710511297532028),
		g.FromCanonicalUint64(1411266850385657080),
		g.FromCanonicalUint64(9024840976168649958),
		g.FromCanonicalUint64(14047056970978379368),
		g.FromCanonicalUint64(838728605080212101),
	}

	// Taken from Plonk3 Poseidon2 implementation. https://github.com/Plonky3/Plonky3/blob/eeb4e37b20127c4daa871b2bad0df30a7c7380db/goldilocks/src/poseidon2.rs#L28
	MATRIX_DIAG_12_U64 = [WIDTH]g.GoldilocksField{
		g.FromCanonicalUint64(0xc3b6c08e23ba9300),
		g.FromCanonicalUint64(0xd84b5de94a324fb6),
		g.FromCanonicalUint64(0x0d0c371c5b35b84f),
		g.FromCanonicalUint64(0x7964f570e7188037),
		g.FromCanonicalUint64(0x5daf18bbd996604b),
		g.FromCanonicalUint64(0x6743bc47b9595257),
		g.FromCanonicalUint64(0x5528b9362c59bb70),
		g.FromCanonicalUint64(0xac45e25b7127b68b),
		g.FromCanonicalUint64(0xa2077d7dfbb606b5),
		g.FromCanonicalUint64(0xf3faac6faee378ae),
		g.FromCanonicalUint64(0x0c6388b51545e883),
		g.FromCanonicalUint64(0xd27dbb6944917b60),
	}
)
